const runQuery = (handler, query) =>
  handler(query).then(r => {
    if (r.errors) {
      throw new Error(r.errors.join(`, `))
    }

    return r.data
  })

const defaultOptions = {
  query: `
      {
        allMarkdownRemark(
          limit: 1000,
        ) {
          edges {
            node {
              frontmatter {
                uid
                lastName
                firstName
                workEmail
                cellPhone
                title
             }
            }
          }
        }
      }
    `,

  // Where we will save the vcf files generated by this query.
  outputPath: `/vcards`,
}

module.exports = {
  runQuery,
  defaultOptions,
}
